# Generated by Django 4.2.6 on 2023-10-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='name',
            field=models.TextField(default='123', max_length=20),
        ),
    ]
